MySQL:
  host: localhost
  port: 3306
  database: minecraft
  username: minecraft
  password: minecraft1234
MeltingFurnace:
  UI_DisplayName: ""
  BlockDisplayName: Ruby Ore
PlantSeparator:
  UI_DisplayName: PlantSeparatorUI
  BlockDisplayName: Mysterious Ore